api = "0.10"

[buildpack]
id = "luban-ci/python-uv"
version = "0.0.9"
name = "Python uv Buildpack"
homepage = "https://github.com/metasync/luban-ci"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"
