apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-prd
  namespace: argocd
spec:
  description: DevOps team project for production environment
  sourceRepos:
    - https://github.com/metasync/*
  destinations:
    - namespace: luban-ci
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
