apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: luban-stack
spec:
  id: "io.buildpacks.stacks.luban"
  buildImage:
    image: "quay.io/luban-ci/luban-build:al2023-cd44607e7057766d99e34cbee6a53e4b0b21dda63159682abb09dc99e9b50480"
  runImage:
    image: "quay.io/luban-ci/luban-run:al2023-b85157b60a7cd3ca323f600326b1eb38f6617eba5bc26993334f7d1977dfe679"
