apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: luban-stack
spec:
  id: "io.buildpacks.stacks.luban"
  buildImage:
    image: "quay.io/luban-ci/luban-build:al2023-3dbd5ee1e5066a86368801de191741605af4893f30cdff78f18c8a1c685a745b"
  runImage:
    image: "quay.io/luban-ci/luban-run:al2023-3d0f957b3aeabcf67bc3488df65e7c72d7934230b761745804de0d4f84decf50"
