apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: luban-ci-kpack-
  namespace: luban-ci
spec:
  workflowTemplateRef:
    name: luban-ci-kpack-template
  arguments:
    parameters:
    - name: repo_url
      value: "https://github.com/metasync/luban-hello-world-py.git"
    - name: revision
      value: "main"
    - name: app_name
      value: "luban-hello-world-py"
    - name: quay_namespace
      value: "luban-ci"
    - name: stack_tag
      value: "al2023"
    - name: sub_path
      value: ""
