apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: luban-ci-kpack-
  namespace: luban-ci
spec:
  workflowTemplateRef:
    name: luban-ci-kpack-template
  arguments:
    parameters:
    - name: repo_url
      value: "https://github.com/metasync/luban-hello-world-py.git"
    - name: revision
      value: ""
    - name: app_name
      value: "luban-hello-world-py"
    - name: sub_path
      value: ""
    - name: git_ref
      value: ""
      # value: "refs/heads/main"
    - name: tag
      value: "0.1.0"
    - name: git_provider
      value: "github"
    - name: git_creds_secret
      value: "github-creds"
    - name: registry_server
      value: "harbor.k8s.orb.local"
    - name: gitops_branch
      value: "develop"
    - name: deploy_env
      value: "snd"
    