apiVersion: v1
kind: ConfigMap
metadata:
  name: luban-config
  namespace: luban-ci
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  default_image_name: "quay.io/luban-ci/luban-hello-world-py"
  default_image_tag: "latest"
  default_container_port: "8000"
  default_service_port: "80"
  domain_suffix: "apps.metasync.cc"
  registry_server: "harbor.luban.metasync.cc"
  image_pull_secret: "harbor-ro-creds"
