apiVersion: v1
kind: ServiceAccount
metadata:
  name: luban-ci-sa
  namespace: luban-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: luban-ci-role
  namespace: luban-ci
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: luban-ci-rb
  namespace: luban-ci
subjects:
- kind: ServiceAccount
  name: luban-ci-sa
  namespace: luban-ci
roleRef:
  kind: Role
  name: luban-ci-role
  apiGroup: rbac.authorization.k8s.io
