apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orb-wildcard-tls
  namespace: gateway
spec:
  secretName: orb-wildcard-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.orb.metasync.cc"
  - "orb.metasync.cc"
