apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.app_name}}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{cookiecutter.service_port}}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{cookiecutter.app_name}}
