apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: luban-hello-world-py
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/metasync/luban-ci.git
    targetRevision: main
    path: manifests/apps/luban-hello-world-py
  destination:
    server: https://kubernetes.default.svc
    namespace: luban-ci
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
