apiVersion: v1
kind: ConfigMap
metadata:
  name: github-config
  namespace: luban-ci
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  server: "github.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-config
  namespace: luban-ci
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  server: "dev.azure.com"
