apiVersion: v1
kind: ConfigMap
metadata:
  name: luban-config
  namespace: luban-ci
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  # Domain suffix
  domain_suffix: "apps.metasync.cc"

  # Registry server
  registry_server: "harbor.luban.metasync.cc"
  image_pull_secret: "harbor-ro-creds"

  # Web Hook URL
  webhook_url: "https://webhook-luban.metasync.cc"
  # webhook_url: "https://webhook.luban.metasync.cc"

  # Git providers
  github_server: "github.com"
  azure_server: "dev.azure.com"

  # Tooling Images
  luban_provisioner_image: "quay.io/luban-ci/luban-provisioner:0.1.196"
  gitops_utils_image: "quay.io/luban-ci/gitops-utils:0.3.7"
