apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/name: {{cookiecutter.app_name}}
      app.kubernetes.io/part-of: {{cookiecutter.project_name}}
    includeSelectors: true
    includeTemplates: true
