apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: "{{cookiecutter.app_name}}"
      app.kubernetes.io/part-of: "{{cookiecutter.project_name}}"
    includeSelectors: true
    includeTemplates: true

vars:
  - name: DAGSTER_APP_IMAGE
    objref:
      kind: Deployment
      name: "{{cookiecutter.app_name}}"
      apiVersion: apps/v1
    fieldref:
      fieldPath: spec.template.spec.containers.0.image
