apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.app_name}}
  labels:
    app: {{cookiecutter.app_name}}
spec:
  ports:
    - port: {{cookiecutter.code_location_port}}
      targetPort: {{cookiecutter.code_location_port}}
      name: grpc
  selector:
    app: {{cookiecutter.app_name}}
