description = "Luban CI Builder"

[[buildpacks]]
  uri = "../buildpacks/python-uv"
  version = "0.0.9"

[lifecycle]
  uri = "cache/lifecycle.tgz"

[[order]]
  [[order.group]]
    id = "luban-ci/python-uv"
    version = "0.0.9"

[[targets]]
  os = "linux"
  arch = "amd64"

[build]
  image = "quay.io/luban-ci/luban-build:al2023"

[run]
  [[run.images]]
    image = "quay.io/luban-ci/luban-run:al2023"
