apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres
  - dagster

labels:
  - pairs:
      app.kubernetes.io/name: "{{cookiecutter.app_name}}"
      app.kubernetes.io/part-of: "{{cookiecutter.project_name}}"
    includeSelectors: true
    includeTemplates: true
