apiVersion: v1
kind: Service
metadata:
  name: luban-hello-world-py
  namespace: luban-ci
  labels:
    app: luban-hello-world-py
spec:
  selector:
    app: luban-hello-world-py
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
