apiVersion: v1
kind: ServiceAccount
metadata:
  name: luban-ci-sa
  namespace: luban-ci
imagePullSecrets:
- name: quay-creds
- name: harbor-creds
secrets:
- name: quay-creds
- name: harbor-creds
- name: github-creds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: luban-ci-cluster-role
rules:
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts", "namespaces"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings", "roles", "clusterrolebindings"]
  verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "patch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "clusterworkflowtemplates"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: luban-ci-crb
subjects:
- kind: ServiceAccount
  name: luban-ci-sa
  namespace: luban-ci
roleRef:
  kind: ClusterRole
  name: luban-ci-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: luban-ci-rbac-escalation-role
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["bind", "escalate"]
  resourceNames: ["admin", "edit", "luban-view-templates", "luban-kpack-reader", "luban-kpack-admin"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: luban-ci-rbac-escalation-crb
subjects:
- kind: ServiceAccount
  name: luban-ci-sa
  namespace: luban-ci
roleRef:
  kind: ClusterRole
  name: luban-ci-rbac-escalation-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: luban-ci-argocd-role
  namespace: argocd
rules:
- apiGroups: ["argoproj.io"]
  resources: ["appprojects", "applications"]
  verbs: ["create", "get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: luban-ci-argocd-rb
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: luban-ci-sa
  namespace: luban-ci
roleRef:
  kind: Role
  name: luban-ci-argocd-role
  apiGroup: rbac.authorization.k8s.io
